//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal_v1 {
    
    
    public partial class _default {
        
        /// <summary>
        /// Manset1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal_v1.user_controls.Manset1 Manset1;
        
        /// <summary>
        /// ucPrj_Hzmt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal_v1.user_controls.proj_hizmt ucPrj_Hzmt;
        
        /// <summary>
        /// ucCarusel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal_v1.user_controls.carusel ucCarusel;
        
        /// <summary>
        /// ucInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal_v1.user_controls.Iletisim.info ucInfo;
        
        /// <summary>
        /// ucDyr_Hbr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal_v1.user_controls.dyr_hbr ucDyr_Hbr;
    }
}
